use_frameworks!

platform :ios, '8.0'

target 'TLCoreKit_Example' do
  pod 'TLCoreKit', :path => '../'

  target 'TLCoreKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
