source 'https://github.com/TeamLiquid2019/TLFoundationSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TLCoreKit_Example' do
  pod 'TLCoreKit', :path => '../'

  target 'TLCoreKit_Tests' do
    inherit! :search_paths
    
  end
end
